-- User and basic reference
\i './app/Tables/user_login.sql'
\i './app/Tables/provider_type.sql'
\i './app/Tables/auth_provider.sql'
\i './app/Tables/user_auth_provider.sql'
\i './app/Tables/role.sql'
\i './app/Tables/user_role.sql'
\i './app/Tables/region.sql'
\i './app/Tables/state.sql'
\i './app/Tables/city.sql'
\i './app/Tables/neighborhood.sql'
\i './app/Tables/street.sql'
\i './app/Tables/address.sql'
\i './app/Tables/user_info.sql'
\i './app/Tables/error_log.sql'


\i './app/Tables/year.sql'
\i './app/Tables/university.sql'
\i './app/Tables/academic_organization.sql'
\i './app/Tables/university_category.sql'
\i './app/Tables/campus.sql'
\i './app/Tables/region.sql'
\i './app/Tables/degree.sql'
\i './app/Tables/degree_level.sql'
\i './app/Tables/shift.sql'
\i './app/Tables/frequency.sql'
\i './app/Tables/quota_type.sql'
\i './app/Tables/special_quota.sql'
\i './app/Tables/seats.sql'
\i './app/Tables/booklet_color.sql'
\i './app/Tables/area.sql'
\i './app/Tables/exam_day.sql'
\i './app/Tables/booklet.sql'



-- Stored Procedures
\i './app/StoredProcedures/usp_api_user_auth_provider_create.sql'
\i './app/StoredProcedures/usp_api_user_email_verification_confirm_token.sql'
\i './app/StoredProcedures/usp_api_user_email_verification_confirm.sql'
\i './app/StoredProcedures/usp_api_user_email_verification_create.sql'
\i './app/StoredProcedures/usp_api_user_email_verification_regenerate.sql'
\i './app/StoredProcedures/usp_api_user_email_verification_validate_token.sql'
\i './app/StoredProcedures/usp_api_user_login_add_password.sql'
\i './app/StoredProcedures/usp_api_user_login_authenticate.sql'
\i './app/StoredProcedures/usp_api_user_login_external_create.sql'
\i './app/StoredProcedures/usp_api_user_login_lock_reset.sql'
\i './app/StoredProcedures/usp_api_user_login_password_reset.sql'
\i './app/StoredProcedures/usp_api_user_login_soft_delete.sql'
\i './app/StoredProcedures/usp_api_user_register_create.sql'
\i './app/StoredProcedures/usp_api_year_create.sql'
\i './app/StoredProcedures/usp_api_academic_organization_create.sql'
\i './app/StoredProcedures/usp_api_university_category_create.sql'
\i './app/StoredProcedures/usp_api_campus_create.sql'
\i './app/StoredProcedures/usp_api_region_create.sql'
\i './app/StoredProcedures/usp_api_degree_create.sql'
\i './app/StoredProcedures/usp_api_degree_level_create.sql'
\i './app/StoredProcedures/usp_api_shift_create.sql'
\i './app/StoredProcedures/usp_api_frequency_create.sql'
\i './app/StoredProcedures/usp_api_quota_type_create.sql'
\i './app/StoredProcedures/usp_quote_type_flags_update.sql'
\i './app/StoredProcedures/usp_api_special_quota_create.sql'
\i './app/StoredProcedures/usp_special_quota_flags_update.sql'
\i './app/StoredProcedures/usp_seats_cutoff_update.sql'
\i './app/StoredProcedures/usp_api_booklet_color_create.sql'
\i './app/StoredProcedures/usp_api_area_create.sql'
\i './app/StoredProcedures/usp_api_exam_day_create.sql'
\i './app/StoredProcedures/usp_api_booklet_create.sql'
\i './app/StoredProcedures/usp_batch_booklets_create.sql'


--Functions
\i './app/Functions/fn_number_to_words_ptbr.sql'
\i './app/Functions/set_year_name_friendly.sql'
\i './app/Functions/set_university_name_friendly.sql'
\i './app/Functions/set_academic_organization_name_friendly.sql'
\i './app/Functions/set_university_category_name_friendly.sql'
\i './app/Functions/set_campus_name_friendly.sql'
\i './app/Functions/set_region_name_friendly.sql'
\i './app/Functions/set_state_name_friendly.sql'
\i './app/Functions/set_city_name_friendly.sql'
\i './app/Functions/set_degree_name_friendly.sql'
\i './app/Functions/set_degree_level_name_friendly.sql'
\i './app/Functions/set_shift_name_friendly.sql'
\i './app/Functions/set_frequency_name_friendly.sql'
\i './app/Functions/set_booklet_color_name_friendly.sql'
\i './app/Functions/set_area_name_friendly.sql'

--Triggers
\i './app/Triggers/trg_set_year_name_friendly.sql'
\i './app/Triggers/trg_set_university_name_friendly.sql'
\i './app/Triggers/trg_set_academic_organization_name_friendly.sql'
\i './app/Triggers/trg_set_university_category_name_friendly.sql'
\i './app/Triggers/trg_set_campus_name_friendly.sql'
\i './app/Triggers/trg_set_region_name_friendly.sql'
\i './app/Triggers/trg_set_state_name_friendly.sql'
\i './app/Triggers/trg_set_city_name_friendly.sql'
\i './app/Triggers/trg_set_degree_name_friendly.sql'
\i './app/Triggers/trg_set_degree_level_name_friendly.sql'
\i './app/Triggers/trg_set_shift_name_friendly.sql'
\i './app/Triggers/trg_set_frequency_name_friendly.sql'
\i './app/Triggers/trg_set_booklet_color_name_friendly.sql'
\i './app/Triggers/trg_set_area_name_friendly.sql'


--Add views
\i './app/Views/v_seats_scores.sql'
