CREATE OR REPLACE FUNCTION app.fn_number_to_words_ptbr(year INT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN CASE year
    WHEN 1990 THEN 'mil novecentos e noventa'
    WHEN 1991 THEN 'mil novecentos e noventa e um'
    WHEN 1992 THEN 'mil novecentos e noventa e dois'
    WHEN 1993 THEN 'mil novecentos e noventa e três'
    WHEN 1994 THEN 'mil novecentos e noventa e quatro'
    WHEN 1995 THEN 'mil novecentos e noventa e cinco'
    WHEN 1996 THEN 'mil novecentos e noventa e seis'
    WHEN 1997 THEN 'mil novecentos e noventa e sete'
    WHEN 1998 THEN 'mil novecentos e noventa e oito'
    WHEN 1999 THEN 'mil novecentos e noventa e nove'
    WHEN 2000 THEN 'dois mil'
    WHEN 2001 THEN 'dois mil e um'
    WHEN 2002 THEN 'dois mil e dois'
    WHEN 2003 THEN 'dois mil e três'
    WHEN 2004 THEN 'dois mil e quatro'
    WHEN 2005 THEN 'dois mil e cinco'
    WHEN 2006 THEN 'dois mil e seis'
    WHEN 2007 THEN 'dois mil e sete'
    WHEN 2008 THEN 'dois mil e oito'
    WHEN 2009 THEN 'dois mil e nove'
    WHEN 2010 THEN 'dois mil e dez'
    WHEN 2011 THEN 'dois mil e onze'
    WHEN 2012 THEN 'dois mil e doze'
    WHEN 2013 THEN 'dois mil e treze'
    WHEN 2014 THEN 'dois mil e quatorze'
    WHEN 2015 THEN 'dois mil e quinze'
    WHEN 2016 THEN 'dois mil e dezesseis'
    WHEN 2017 THEN 'dois mil e dezessete'
    WHEN 2018 THEN 'dois mil e dezoito'
    WHEN 2019 THEN 'dois mil e dezenove'
    WHEN 2020 THEN 'dois mil e vinte'
    WHEN 2021 THEN 'dois mil e vinte e um'
    WHEN 2022 THEN 'dois mil e vinte e dois'
    WHEN 2023 THEN 'dois mil e vinte e três'
    WHEN 2024 THEN 'dois mil e vinte e quatro'
    WHEN 2025 THEN 'dois mil e vinte e cinco'
    WHEN 2026 THEN 'dois mil e vinte e seis'
    WHEN 2027 THEN 'dois mil e vinte e sete'
    WHEN 2028 THEN 'dois mil e vinte e oito'
    WHEN 2029 THEN 'dois mil e vinte e nove'
    WHEN 2030 THEN 'dois mil e trinta'
    WHEN 2031 THEN 'dois mil e trinta e um'
    WHEN 2032 THEN 'dois mil e trinta e dois'
    WHEN 2033 THEN 'dois mil e trinta e três'
    WHEN 2034 THEN 'dois mil e trinta e quatro'
    WHEN 2035 THEN 'dois mil e trinta e cinco'
    WHEN 2036 THEN 'dois mil e trinta e seis'
    WHEN 2037 THEN 'dois mil e trinta e sete'
    WHEN 2038 THEN 'dois mil e trinta e oito'
    WHEN 2039 THEN 'dois mil e trinta e nove'
    WHEN 2040 THEN 'dois mil e quarenta'
    WHEN 2041 THEN 'dois mil e quarenta e um'
    WHEN 2042 THEN 'dois mil e quarenta e dois'
    WHEN 2043 THEN 'dois mil e quarenta e três'
    WHEN 2044 THEN 'dois mil e quarenta e quatro'
    WHEN 2045 THEN 'dois mil e quarenta e cinco'
    WHEN 2046 THEN 'dois mil e quarenta e seis'
    WHEN 2047 THEN 'dois mil e quarenta e sete'
    WHEN 2048 THEN 'dois mil e quarenta e oito'
    WHEN 2049 THEN 'dois mil e quarenta e nove'
    WHEN 2050 THEN 'dois mil e cinquenta'
    ELSE NULL
  END;
END;
$$;
