create table if not exists imp.enem_cutoff_scores_2019_2024
(
    edicao varchar(100),
    nu_ano int,
    nu_edicao smallint,
	co_ies int,
	no_ies varchar(100),
	sg_ies varchar(100),
    ds_organizacao_academica text,
	ds_categoria_adm text,
	co_campus int,
	no_campus varchar(100),
	no_municipio_campus varchar(100),
	sg_uf_campus varchar(100),
	ds_regiao_campus text,
	co_ies_curso int,
	no_curso varchar(100),
	ds_grau text,
	ds_turno text,
    tp_modalidade varchar(100),
	tp_mod_concorrencia varchar(100),
    tipo_concorrencia varchar(100),
	ds_mod_concorrencia text,
    nu_percentual_bonus smallint,
    qt_vagas_concorrencia smallint,
	qt_vagas_ofertadas smallint,
    nu_notacorte smallint,
    qt_inscricao smallint
);