CREATE TABLE IF NOT EXISTS imp.enem_microdata (
    enem_microdata_id        SERIAL,
    enem_registration        VARCHAR(20) NOT NULL,
    exam_year                SMALLINT NOT NULL,
    age_group_code           SMALLINT,
    gender                   CHAR(1),
    marital_status_code      SMALLINT,
    race_code                SMALLINT,
    nationality_code         SMALLINT,
    completion_status_code   SMALLINT,
    year_completed           SMALLINT,
    school_type_code         SMALLINT,
    school_teaching_type     SMALLINT,
    is_treineiro             SMALLINT,
    school_city_code         INTEGER,
    school_city_name         TEXT,
    school_state_code        SMALLINT,
    school_state_abbr        CHAR(2),
    school_dependency_code   SMALLINT,
    school_location_code     SMALLINT,
    school_status_code       SMALLINT,
    exam_city_code           INTEGER,
    exam_city_name           TEXT,
    exam_state_code          SMALLINT,
    exam_state_abbr          CHAR(2),
    present_sciences         SMALLINT,
    present_humanities       SMALLINT,
    present_languages        SMALLINT,
    present_math             SMALLINT,
    prova_code_sciences      VARCHAR(10),
    prova_code_humanities    VARCHAR(10),
    prova_code_languages     VARCHAR(10),
    prova_code_math          VARCHAR(10),
    score_sciences           NUMERIC(6,2),
    score_humanities         NUMERIC(6,2),
    score_languages          NUMERIC(6,2),
    score_math               NUMERIC(6,2),
    answers_sciences         TEXT,
    answers_humanities       TEXT,
    answers_languages        TEXT,
    answers_math             TEXT,
    language_choice_code     SMALLINT,
    gabarito_sciences        TEXT,
    gabarito_humanities      TEXT,
    gabarito_languages       TEXT,
    gabarito_math            TEXT,
    essay_status_code        SMALLINT,
    essay_comp1_score        NUMERIC(5,2),
    essay_comp2_score        NUMERIC(5,2),
    essay_comp3_score        NUMERIC(5,2),
    essay_comp4_score        NUMERIC(5,2),
    essay_comp5_score        NUMERIC(5,2),
    essay_total_score        NUMERIC(6,2),
    -- Socio-economic questionnaire Q001 to Q025
    q001                     CHAR(1),
    q002                     CHAR(1),
    q003                     CHAR(1),
    q004                     CHAR(1),
    q005                     CHAR(1),
    q006                     CHAR(1),
    q007                     CHAR(1),
    q008                     CHAR(1),
    q009                     CHAR(1),
    q010                     CHAR(1),
    q011                     CHAR(1),
    q012                     CHAR(1),
    q013                     CHAR(1),
    q014                     CHAR(1),
    q015                     CHAR(1),
    q016                     CHAR(1),
    q017                     CHAR(1),
    q018                     CHAR(1),
    q019                     CHAR(1),
    q020                     CHAR(1),
    q021                     CHAR(1),
    q022                     CHAR(1),
    q023                     CHAR(1),
    q024                     CHAR(1),
    q025                     CHAR(1),
    created_by               TEXT NOT NULL,
    created_on               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_by              TEXT,
    modified_on              TIMESTAMPTZ,
    -- Constraints
    CONSTRAINT pk_enem_microdata_id PRIMARY KEY (enem_microdata_id),
    CONSTRAINT uq_enem_microdata UNIQUE (enem_registration, exam_year)
);
