CREATE TABLE IF NOT EXISTS imp.exam_source (
    exam_source_id  BIGSERIAL PRIMARY KEY,
    exam_year       SMALLINT       NOT NULL,
    test_code       TEXT           NOT NULL,  -- e.g., 'P1'
    notebook_code   TEXT           NOT NULL,  -- e.g., 'CAD_01'
    day_code        TEXT           NOT NULL,  -- e.g., 'DIA_1'
    color_name      TEXT           NOT NULL,  -- e.g., 'AZUL'
    source_pdf_path TEXT,
    payload         JSONB          NOT NULL,  -- full JSON as generated by Python
    CONSTRAINT uq_exam_source_meta UNIQUE (exam_year, test_code, notebook_code, day_code, color_name)
);