CREATE TABLE IF NOT EXISTS imp.sisu_spot_cutoff_score (
    sisu_spot_cutoff_id               SERIAL PRIMARY KEY,
    EDICAO                  TEXT,
    CO_IES                  TEXT,
    NO_IES                  TEXT,
    SG_IES                  TEXT,
    DS_ORGANIZACAO_ACADEMICA TEXT,
    DS_CATEGORIA_ADM        TEXT,
    NO_CAMPUS               TEXT,
    NO_MUNICIPIO_CAMPUS     TEXT,
    SG_UF_CAMPUS            TEXT,
    DS_REGIAO_CAMPUS        TEXT,
    CO_IES_CURSO            TEXT,
    NO_CURSO                TEXT,
    DS_GRAU                 TEXT,
    DS_TURNO                TEXT,
    TP_MOD_CONCORRENCIA     TEXT,
    TIPO_CONCORRENCIA       TEXT,
    DS_MOD_CONCORRENCIA     TEXT,
    NU_PERCENTUAL_BONUS     NUMERIC(5,2),
    QT_VAGAS_OFERTADAS      NUMERIC(5,2),
    NU_NOTACORTE            NUMERIC(8,2),
    QT_INSCRICAO            NUMERIC
);
