name: Test SSH to Azure VM

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Compress and copy repo to VM
      run: |
        tar czf db_deploy.tar.gz .
        scp -i ~/.ssh/id_rsa db_deploy.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/

    - name: SSH and verify connection
      run: |
        echo "Trying SSH connection..."
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          set -e
          cd /tmp
          tar xzf db_deploy.tar.gz
          cd db_deploy

          export PGPASSWORD="${{ secrets.DB_PASS }}"
          echo "Running master_script.sql..."
          psql -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -v ON_ERROR_STOP=1 -f master_script.sql

          echo "DB Deploy Complete"
          rm -rf /tmp/db_deploy /tmp/db_deploy.tar.gz
        EOF
