name: Test SSH to Azure VM

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Reconstruct Config.sql from secret
      run: |
        echo "${{ secrets.CONFIG_SQL_B64 }}" | base64 -d > Config.sql

    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy SQL files and folders to VM
      run: |
        mkdir upload
        cp master_script.sql Config.sql upload/
        cp -r app stg imp schemas.sql extensions.sql DropTable.sql seed.sql upload/
        scp -i ~/.ssh/id_rsa -r upload ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/

    - name: SSH and verify connection
      run: |
        echo "Trying SSH connection..."
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          set -e
          cd /tmp/upload
          export PGPASSWORD="${{ secrets.DB_PASS }}"
          echo "Running master_script.sql..."
          psql -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -v ON_ERROR_STOP=1 -f master_script.sql
          echo "DB Deploy Complete"
          rm -rf /tmp/upload
        EOF
