name: Deploy PostgreSQL from GitHub Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH access to Azure VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy full repo to Azure VM
      run: |
        scp -i ~/.ssh/id_rsa -r . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/db_deploy/

    - name: Run master_script.sql on remote PostgreSQL
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          set -e
          export PGPASSWORD="${{ secrets.DB_PASS }}"
          echo "Running master_script.sql..."
          cd /tmp/db_deploy
          psql -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -v ON_ERROR_STOP=1 -f master_script.sql
          echo "Cleaning up..."
          rm -rf /tmp/db_deploy
        EOF
